# By default, standard app engine variant is used
runtime: java11
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 100
  max_concurrent_requests: 50
env_variables:
  GCLOUD_BUCKET: $GCLOUD_BUCKET
  GCLOUD_PROJECT: $GCLOUD_PROJECT
  