# By default, standard app engine variant is used
# https://cloud.google.com/appengine/docs/standard/java11/config/appref
runtime: java11
inbound_services:
  - warmup
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5
  # Idle instances do not serve traffic, but are kept warm in
  # case of a traffic spike
  min_idle_instances: 1
  # max_idle_instances: 4
  max_concurrent_requests: 50
env_variables:
  GCLOUD_BUCKET: $GCLOUD_BUCKET
  GCLOUD_PROJECT: $GCLOUD_PROJECT
  