# By default, standard app engine variant is used
# https://cloud.google.com/appengine/docs/standard/java11/config/appref
runtime: java11
automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 5
  max_concurrent_requests: 50
env_variables:
  GCLOUD_BUCKET: $GCLOUD_BUCKET
  GCLOUD_PROJECT: $GCLOUD_PROJECT
  